#List of death messages that will be randomized
death-messages:
  - was slaughtered by
  - took an L to
  - got railed by
  - was folded by
  - got tossed by
  - was clowned on by

#The color for the death messages
#Available variables: {player}, {msg}, {killer}, {hp}
#Player is the player that died, msg is the random chosen message, hp is the killers remaining health.
format: "§c{player} §3{msg} §c{killer} §7[{hp} HP]"

#The cooldown in seconds of slime blocks launching you in the air.
slime-cooldown: 15

#Use {slimecooldown} to replace the seconds left in the cooldown.
slimecooldown-message: "§eYou are on cooldown! You can use this ability again in {slimecooldown} seconds!"

#The cooldown in seconds for ender pearls
pearl-cooldown: 15

#Use {pearlcooldown} to replace the seconds left in the cooldown.
pearlcd-message: "§9You are on cooldown! You can throw an ender pearl again in §b{pearlcooldown} §9seconds!"

#The cooldown in seconds for golden apples
gapple-cooldown: 15

#Use {gapplecooldown} to replace the seconds left in the cooldown.
gapplecd-message: "§gYou are on cooldown! You can eat a Golden Apple again in §c{gapplecooldown} §gseconds!"

#Use {amount-cleared} for the amount of entities that were cleared.
#Use true / false, if broadcast cleared is true, a mesage will be broadcasted each time entities are cleared
broadcast-cleared: true

#This will only work if broadcast-cleared is set to true
clear-entities-message: "{amount-cleared} §bentities were cleared."

#The interval in seconds to clear entities
clear-entities-interval: 300

##Below is the configuration for the combat logger:

#How long the combat timer lasts for (in seconds)
combat-time: 15

#The message sent to the player when they enter combat
combat-message: '§cYou are now in combat!'

#The message sent to the player when they are out of combat
combat-leave: '§aYou are now out of combat!'

#The message sent to the player when they try to use a disallowed command in combat
command-message: "§cYou cannot use this command while in combat!"

#Commands to disallow in combat (cant use these commands in combat)
combat-commands:
  - spawn
  - hub
  - kit

#If the default rank does not exist in ranks.json it will automatically be created.
#IMPORTANT >> Default rank is case sensitive. << IMPORTANT
default-rank: "Player"

#Commands to unregister (disable), don't add the /
commands-unregistered:
  - 'me'
  - 'reload'
  - 'seed'
  - 'particle'